Add vue lazyload
DivanteLtd/vsf-default pull request #36
Opened 2020-10-20 15:55 UTC by jahvi

### Related Issues

https://github.com/DivanteLtd/vue-storefront/issues/4998

### Short Description and Why It's Useful

Add vue-lazyload as a dependency as it will be removed from the core.

Related PR: https://github.com/DivanteLtd/vue-storefront/pull/5045

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-default/blob/master/CONTRIBUTING.md)

2020-10-20 17:33 UTC, gibkigonzo commented on index.js
> +Vue.use(VueLazyload)
add same options that are used in core `Vue.use(VueLazyload, { attempt: 2, preLoad: 1.5 })`

2020-10-20 17:37 UTC, gibkigonzo commented
This should be merged just before 1.13 release. Because develop branch is used for minor (1.13) and patch version (1.12.x). We don't want to add this for patch version of vsf.

2020-10-20 17:42 UTC, jahvi commented
Done, updated changelog as well, let me know if you need me to change anything else.

2020-10-21 09:13 UTC, Fifciu requested changes
You have to register plugins inside `once` to prevent memory leaks:
```
once('__VUE_EXTEND_DROPPOINT_VPB__', () => {
 // Here!
})
```

2020-10-21 18:11 UTC, jahvi commented
@Fifciu My bad, this should be fixed now

2020-10-28 10:03 UTC, Fifciu approved these changes

2020-11-07 18:06 UTC, Fifciu approved these changes

2020-11-07 18:08 UTC, merged